# Generated by Django 6.0.1 on 2026-02-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='child',
            name='updated_at',
        ),
    ]
